# Generated by Django 5.0.2 on 2024-08-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend_movie_rec', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='movie_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('movie_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User_data',
        ),
    ]
